// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TemplateCRUDNet7.Context;

#nullable disable

namespace TemplateCRUDNet7.Migrations
{
    [DbContext(typeof(TemplateContext))]
    [Migration("20231127202700_InitialTaskManagement")]
    partial class InitialTaskManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TemplateCRUDNet7.Entities.Tasks", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameTask")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TASKS");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3e76d582-7158-4529-ba03-fbb427fdc3fc"),
                            DateCreated = new DateTime(2023, 11, 28, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(2665),
                            Description = "generar el jwt",
                            IsCompleted = false,
                            IsDeleted = false,
                            NameTask = "Tarea 1",
                            UserId = new Guid("09545053-100d-4d65-b5f4-30dc76de76f5")
                        },
                        new
                        {
                            Id = new Guid("0302f8f8-db25-43e6-bff5-f511a43800e0"),
                            DateCreated = new DateTime(2023, 11, 29, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(2771),
                            Description = "eliminar una tarea",
                            IsCompleted = true,
                            IsDeleted = false,
                            NameTask = "Tarea 2",
                            UserId = new Guid("09545053-100d-4d65-b5f4-30dc76de76f5")
                        },
                        new
                        {
                            Id = new Guid("99e35573-3840-415d-beb4-5ca7bfc1419a"),
                            DateCreated = new DateTime(2023, 11, 30, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(2780),
                            Description = "agregar una tarea al backlog",
                            IsCompleted = false,
                            IsDeleted = false,
                            NameTask = "Tarea 3",
                            UserId = new Guid("3c85ef10-5ed2-4563-9f2d-600f9d01397b")
                        },
                        new
                        {
                            Id = new Guid("aab0af23-e589-4f73-95fd-8ea73b4d93f3"),
                            DateCreated = new DateTime(2023, 12, 1, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(2788),
                            Description = "agregar una tarea al backlog",
                            IsCompleted = true,
                            IsDeleted = false,
                            NameTask = "Tarea 4",
                            UserId = new Guid("a73c074a-cf36-42d7-a21d-c2912ac8031a")
                        },
                        new
                        {
                            Id = new Guid("45493534-b7df-47ef-9ea7-657955bb3cb1"),
                            DateCreated = new DateTime(2023, 12, 2, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(2796),
                            Description = "agregar una tarea al backlog",
                            IsCompleted = false,
                            IsDeleted = false,
                            NameTask = "Tarea 5",
                            UserId = new Guid("a73c074a-cf36-42d7-a21d-c2912ac8031a")
                        },
                        new
                        {
                            Id = new Guid("03841d45-17a4-4350-b624-c426db30db5c"),
                            DateCreated = new DateTime(2023, 12, 3, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(2807),
                            Description = "agregar una tarea al backlog",
                            IsCompleted = true,
                            IsDeleted = false,
                            NameTask = "Tarea 6",
                            UserId = new Guid("3c85ef10-5ed2-4563-9f2d-600f9d01397b")
                        },
                        new
                        {
                            Id = new Guid("320e503f-e352-44e7-9c90-e74ecdc191fd"),
                            DateCreated = new DateTime(2023, 12, 4, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(2815),
                            Description = "agregar una tarea al backlog",
                            IsCompleted = false,
                            IsDeleted = false,
                            NameTask = "Tarea 7",
                            UserId = new Guid("09545053-100d-4d65-b5f4-30dc76de76f5")
                        },
                        new
                        {
                            Id = new Guid("6018f5fe-6be2-4965-869b-ee4ef94cb66f"),
                            DateCreated = new DateTime(2023, 12, 5, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(2821),
                            Description = "agregar una tarea al backlog",
                            IsCompleted = true,
                            IsDeleted = false,
                            NameTask = "Tarea 8",
                            UserId = new Guid("a73c074a-cf36-42d7-a21d-c2912ac8031a")
                        },
                        new
                        {
                            Id = new Guid("f5a5ed65-6a60-418f-88f1-e3a18b1a68dd"),
                            DateCreated = new DateTime(2023, 12, 6, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(2832),
                            Description = "eliminar una tarea",
                            IsCompleted = false,
                            IsDeleted = false,
                            NameTask = "Tarea 9",
                            UserId = new Guid("3c85ef10-5ed2-4563-9f2d-600f9d01397b")
                        },
                        new
                        {
                            Id = new Guid("f26bb131-f79e-47b8-ac21-6c56cce6f415"),
                            DateCreated = new DateTime(2023, 12, 7, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(2842),
                            Description = "hacer el login",
                            IsCompleted = true,
                            IsDeleted = false,
                            NameTask = "Tarea 10",
                            UserId = new Guid("3c85ef10-5ed2-4563-9f2d-600f9d01397b")
                        },
                        new
                        {
                            Id = new Guid("a413d69e-f203-4616-bc52-d88ebc76f009"),
                            DateCreated = new DateTime(2023, 12, 8, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(2881),
                            Description = "agregar una tarea al backlog",
                            IsCompleted = false,
                            IsDeleted = false,
                            NameTask = "Tarea 11",
                            UserId = new Guid("a73c074a-cf36-42d7-a21d-c2912ac8031a")
                        },
                        new
                        {
                            Id = new Guid("e00b644a-f8dd-4191-aea4-43decc98cea0"),
                            DateCreated = new DateTime(2023, 12, 9, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(2889),
                            Description = "agregar una tarea al backlog",
                            IsCompleted = true,
                            IsDeleted = false,
                            NameTask = "Tarea 12",
                            UserId = new Guid("09545053-100d-4d65-b5f4-30dc76de76f5")
                        },
                        new
                        {
                            Id = new Guid("4edb9109-9e17-4595-81d8-47c16adc2441"),
                            DateCreated = new DateTime(2023, 12, 10, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(2897),
                            Description = "agregar una tarea al backlog",
                            IsCompleted = false,
                            IsDeleted = false,
                            NameTask = "Tarea 13",
                            UserId = new Guid("09545053-100d-4d65-b5f4-30dc76de76f5")
                        },
                        new
                        {
                            Id = new Guid("92cf422c-52d9-44a5-b402-efa66f391a9b"),
                            DateCreated = new DateTime(2023, 12, 11, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(2904),
                            Description = "hacer el login",
                            IsCompleted = true,
                            IsDeleted = false,
                            NameTask = "Tarea 14",
                            UserId = new Guid("3c85ef10-5ed2-4563-9f2d-600f9d01397b")
                        },
                        new
                        {
                            Id = new Guid("84c092ad-8f7c-4492-90f5-0f24b5790704"),
                            DateCreated = new DateTime(2023, 12, 12, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(2910),
                            Description = "hacer el login",
                            IsCompleted = false,
                            IsDeleted = false,
                            NameTask = "Tarea 15",
                            UserId = new Guid("09545053-100d-4d65-b5f4-30dc76de76f5")
                        },
                        new
                        {
                            Id = new Guid("b70206e2-84d2-4385-a08e-58388b85d8fa"),
                            DateCreated = new DateTime(2023, 12, 13, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(2917),
                            Description = "hacer el login",
                            IsCompleted = true,
                            IsDeleted = false,
                            NameTask = "Tarea 16",
                            UserId = new Guid("09545053-100d-4d65-b5f4-30dc76de76f5")
                        },
                        new
                        {
                            Id = new Guid("6c9c8c65-c1ab-4f62-8ec9-2311ad73fafc"),
                            DateCreated = new DateTime(2023, 12, 14, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(2926),
                            Description = "eliminar una tarea",
                            IsCompleted = false,
                            IsDeleted = false,
                            NameTask = "Tarea 17",
                            UserId = new Guid("09545053-100d-4d65-b5f4-30dc76de76f5")
                        },
                        new
                        {
                            Id = new Guid("20657245-8c4d-483e-9abd-d6ad019bc0b6"),
                            DateCreated = new DateTime(2023, 12, 15, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(2936),
                            Description = "generar el jwt",
                            IsCompleted = true,
                            IsDeleted = false,
                            NameTask = "Tarea 18",
                            UserId = new Guid("a73c074a-cf36-42d7-a21d-c2912ac8031a")
                        },
                        new
                        {
                            Id = new Guid("4ec63f6d-1573-45a7-ab02-540232fe107e"),
                            DateCreated = new DateTime(2023, 12, 16, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(2943),
                            Description = "eliminar una tarea",
                            IsCompleted = false,
                            IsDeleted = false,
                            NameTask = "Tarea 19",
                            UserId = new Guid("a73c074a-cf36-42d7-a21d-c2912ac8031a")
                        },
                        new
                        {
                            Id = new Guid("031f1070-cfa6-4f30-8c68-70c7d4bede9c"),
                            DateCreated = new DateTime(2023, 12, 17, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(2950),
                            Description = "agregar una tarea al backlog",
                            IsCompleted = true,
                            IsDeleted = false,
                            NameTask = "Tarea 20",
                            UserId = new Guid("09545053-100d-4d65-b5f4-30dc76de76f5")
                        },
                        new
                        {
                            Id = new Guid("8d223f61-967b-4083-ba7e-9ef0da640f20"),
                            DateCreated = new DateTime(2023, 12, 18, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(3013),
                            Description = "generar el jwt",
                            IsCompleted = false,
                            IsDeleted = false,
                            NameTask = "Tarea 21",
                            UserId = new Guid("a73c074a-cf36-42d7-a21d-c2912ac8031a")
                        },
                        new
                        {
                            Id = new Guid("5e737ad7-633b-4637-8a84-cd53d62a55e5"),
                            DateCreated = new DateTime(2023, 12, 19, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(3022),
                            Description = "agregar una tarea al backlog",
                            IsCompleted = true,
                            IsDeleted = false,
                            NameTask = "Tarea 22",
                            UserId = new Guid("a73c074a-cf36-42d7-a21d-c2912ac8031a")
                        },
                        new
                        {
                            Id = new Guid("da28584e-a631-49de-bb73-2fbc273511a4"),
                            DateCreated = new DateTime(2023, 12, 20, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(3029),
                            Description = "eliminar una tarea",
                            IsCompleted = false,
                            IsDeleted = false,
                            NameTask = "Tarea 23",
                            UserId = new Guid("a73c074a-cf36-42d7-a21d-c2912ac8031a")
                        },
                        new
                        {
                            Id = new Guid("1cfa40e0-658f-49b8-901a-9f8dcc693cb5"),
                            DateCreated = new DateTime(2023, 12, 21, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(3036),
                            Description = "agregar una tarea al backlog",
                            IsCompleted = true,
                            IsDeleted = false,
                            NameTask = "Tarea 24",
                            UserId = new Guid("a73c074a-cf36-42d7-a21d-c2912ac8031a")
                        },
                        new
                        {
                            Id = new Guid("d30bd962-ae8c-4fec-822b-a9c6cf3a8952"),
                            DateCreated = new DateTime(2023, 12, 22, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(3047),
                            Description = "generar el jwt",
                            IsCompleted = false,
                            IsDeleted = false,
                            NameTask = "Tarea 25",
                            UserId = new Guid("3c85ef10-5ed2-4563-9f2d-600f9d01397b")
                        },
                        new
                        {
                            Id = new Guid("2fd01184-5bc3-46f0-9903-a9bff961be7a"),
                            DateCreated = new DateTime(2023, 12, 23, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(3054),
                            Description = "hacer el login",
                            IsCompleted = true,
                            IsDeleted = false,
                            NameTask = "Tarea 26",
                            UserId = new Guid("a73c074a-cf36-42d7-a21d-c2912ac8031a")
                        },
                        new
                        {
                            Id = new Guid("2e33b687-6bca-49d5-b723-a4cff44003e1"),
                            DateCreated = new DateTime(2023, 12, 24, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(3061),
                            Description = "agregar una tarea al backlog",
                            IsCompleted = false,
                            IsDeleted = false,
                            NameTask = "Tarea 27",
                            UserId = new Guid("a73c074a-cf36-42d7-a21d-c2912ac8031a")
                        },
                        new
                        {
                            Id = new Guid("27207a42-b790-495b-bc03-34110da5c379"),
                            DateCreated = new DateTime(2023, 12, 25, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(3068),
                            Description = "generar el jwt",
                            IsCompleted = true,
                            IsDeleted = false,
                            NameTask = "Tarea 28",
                            UserId = new Guid("a73c074a-cf36-42d7-a21d-c2912ac8031a")
                        },
                        new
                        {
                            Id = new Guid("8837997a-e342-4059-bfc7-8a296bbb01c9"),
                            DateCreated = new DateTime(2023, 12, 26, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(3074),
                            Description = "eliminar una tarea",
                            IsCompleted = false,
                            IsDeleted = false,
                            NameTask = "Tarea 29",
                            UserId = new Guid("a73c074a-cf36-42d7-a21d-c2912ac8031a")
                        },
                        new
                        {
                            Id = new Guid("e6e5bfa2-8618-4adf-af82-031177e0b1b0"),
                            DateCreated = new DateTime(2023, 12, 27, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(3081),
                            Description = "agregar una tarea al backlog",
                            IsCompleted = true,
                            IsDeleted = false,
                            NameTask = "Tarea 30",
                            UserId = new Guid("3c85ef10-5ed2-4563-9f2d-600f9d01397b")
                        },
                        new
                        {
                            Id = new Guid("6a7f4445-a3e0-44de-b1df-8fbff914f31d"),
                            DateCreated = new DateTime(2023, 12, 28, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(3088),
                            Description = "hacer el login",
                            IsCompleted = false,
                            IsDeleted = false,
                            NameTask = "Tarea 31",
                            UserId = new Guid("a73c074a-cf36-42d7-a21d-c2912ac8031a")
                        },
                        new
                        {
                            Id = new Guid("138c70c7-b804-41e6-a675-4ed095d81d68"),
                            DateCreated = new DateTime(2023, 12, 29, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(3095),
                            Description = "generar el jwt",
                            IsCompleted = true,
                            IsDeleted = false,
                            NameTask = "Tarea 32",
                            UserId = new Guid("a73c074a-cf36-42d7-a21d-c2912ac8031a")
                        },
                        new
                        {
                            Id = new Guid("ab99b95f-ea6d-475a-b1f7-faacda163936"),
                            DateCreated = new DateTime(2023, 12, 30, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(3104),
                            Description = "hacer el login",
                            IsCompleted = false,
                            IsDeleted = false,
                            NameTask = "Tarea 33",
                            UserId = new Guid("a73c074a-cf36-42d7-a21d-c2912ac8031a")
                        },
                        new
                        {
                            Id = new Guid("d2ed0ce4-65e4-4a5b-a6cb-a0ccef47de66"),
                            DateCreated = new DateTime(2023, 12, 31, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(3114),
                            Description = "agregar una tarea al backlog",
                            IsCompleted = true,
                            IsDeleted = false,
                            NameTask = "Tarea 34",
                            UserId = new Guid("09545053-100d-4d65-b5f4-30dc76de76f5")
                        },
                        new
                        {
                            Id = new Guid("fc7572a9-644c-4e4b-83eb-91b4450f02d9"),
                            DateCreated = new DateTime(2024, 1, 1, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(3122),
                            Description = "eliminar una tarea",
                            IsCompleted = false,
                            IsDeleted = false,
                            NameTask = "Tarea 35",
                            UserId = new Guid("3c85ef10-5ed2-4563-9f2d-600f9d01397b")
                        },
                        new
                        {
                            Id = new Guid("2fe952c8-ac08-4682-956d-6a6dcd323ac4"),
                            DateCreated = new DateTime(2024, 1, 2, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(3129),
                            Description = "hacer el login",
                            IsCompleted = true,
                            IsDeleted = false,
                            NameTask = "Tarea 36",
                            UserId = new Guid("09545053-100d-4d65-b5f4-30dc76de76f5")
                        },
                        new
                        {
                            Id = new Guid("5a8c5612-ed9e-493d-930e-020cecdd63b5"),
                            DateCreated = new DateTime(2024, 1, 3, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(3136),
                            Description = "hacer el registro",
                            IsCompleted = false,
                            IsDeleted = false,
                            NameTask = "Tarea 37",
                            UserId = new Guid("3c85ef10-5ed2-4563-9f2d-600f9d01397b")
                        },
                        new
                        {
                            Id = new Guid("fd861f11-f19a-4fb1-9b49-5b1f54b6c419"),
                            DateCreated = new DateTime(2024, 1, 4, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(3142),
                            Description = "eliminar una tarea",
                            IsCompleted = true,
                            IsDeleted = false,
                            NameTask = "Tarea 38",
                            UserId = new Guid("3c85ef10-5ed2-4563-9f2d-600f9d01397b")
                        },
                        new
                        {
                            Id = new Guid("db20a7de-81ab-499d-a195-29c541853d03"),
                            DateCreated = new DateTime(2024, 1, 5, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(3149),
                            Description = "hacer el login",
                            IsCompleted = false,
                            IsDeleted = false,
                            NameTask = "Tarea 39",
                            UserId = new Guid("a73c074a-cf36-42d7-a21d-c2912ac8031a")
                        },
                        new
                        {
                            Id = new Guid("4f505301-c136-4e1e-8a0b-d09629bafb33"),
                            DateCreated = new DateTime(2024, 1, 6, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(3155),
                            Description = "generar el jwt",
                            IsCompleted = true,
                            IsDeleted = false,
                            NameTask = "Tarea 40",
                            UserId = new Guid("3c85ef10-5ed2-4563-9f2d-600f9d01397b")
                        },
                        new
                        {
                            Id = new Guid("f67a5084-cf69-4c9d-8c6c-f54e03260a09"),
                            DateCreated = new DateTime(2024, 1, 7, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(3164),
                            Description = "generar el jwt",
                            IsCompleted = false,
                            IsDeleted = false,
                            NameTask = "Tarea 41",
                            UserId = new Guid("09545053-100d-4d65-b5f4-30dc76de76f5")
                        },
                        new
                        {
                            Id = new Guid("9dda38e1-25d0-4781-8978-3f9d5c4b5bcb"),
                            DateCreated = new DateTime(2024, 1, 8, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(3171),
                            Description = "hacer el login",
                            IsCompleted = true,
                            IsDeleted = false,
                            NameTask = "Tarea 42",
                            UserId = new Guid("a73c074a-cf36-42d7-a21d-c2912ac8031a")
                        },
                        new
                        {
                            Id = new Guid("5c385f9b-3aea-4eeb-ba1e-0a91c02d31c4"),
                            DateCreated = new DateTime(2024, 1, 9, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(3178),
                            Description = "generar el jwt",
                            IsCompleted = false,
                            IsDeleted = false,
                            NameTask = "Tarea 43",
                            UserId = new Guid("3c85ef10-5ed2-4563-9f2d-600f9d01397b")
                        },
                        new
                        {
                            Id = new Guid("2ca45c38-b3dc-4878-b7cd-42b4d3b4fbca"),
                            DateCreated = new DateTime(2024, 1, 10, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(3222),
                            Description = "generar el jwt",
                            IsCompleted = true,
                            IsDeleted = false,
                            NameTask = "Tarea 44",
                            UserId = new Guid("3c85ef10-5ed2-4563-9f2d-600f9d01397b")
                        },
                        new
                        {
                            Id = new Guid("759382d4-c6f7-48ca-b35a-fdfbb1f278e1"),
                            DateCreated = new DateTime(2024, 1, 11, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(3230),
                            Description = "agregar una tarea al backlog",
                            IsCompleted = false,
                            IsDeleted = false,
                            NameTask = "Tarea 45",
                            UserId = new Guid("a73c074a-cf36-42d7-a21d-c2912ac8031a")
                        },
                        new
                        {
                            Id = new Guid("85e81027-2521-4fc3-bec8-06e91e691c86"),
                            DateCreated = new DateTime(2024, 1, 12, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(3237),
                            Description = "hacer el registro",
                            IsCompleted = true,
                            IsDeleted = false,
                            NameTask = "Tarea 46",
                            UserId = new Guid("a73c074a-cf36-42d7-a21d-c2912ac8031a")
                        },
                        new
                        {
                            Id = new Guid("7c6fcf07-5763-4740-a2f1-bd60e6ebb501"),
                            DateCreated = new DateTime(2024, 1, 13, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(3243),
                            Description = "agregar una tarea al backlog",
                            IsCompleted = false,
                            IsDeleted = false,
                            NameTask = "Tarea 47",
                            UserId = new Guid("a73c074a-cf36-42d7-a21d-c2912ac8031a")
                        },
                        new
                        {
                            Id = new Guid("1aaed3bf-da8c-4d7c-8f7f-9d8f20075363"),
                            DateCreated = new DateTime(2024, 1, 14, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(3250),
                            Description = "generar el jwt",
                            IsCompleted = true,
                            IsDeleted = false,
                            NameTask = "Tarea 48",
                            UserId = new Guid("09545053-100d-4d65-b5f4-30dc76de76f5")
                        },
                        new
                        {
                            Id = new Guid("3cbc395b-3504-43fb-8713-90db4366b5b1"),
                            DateCreated = new DateTime(2024, 1, 15, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(3259),
                            Description = "eliminar una tarea",
                            IsCompleted = false,
                            IsDeleted = false,
                            NameTask = "Tarea 49",
                            UserId = new Guid("09545053-100d-4d65-b5f4-30dc76de76f5")
                        },
                        new
                        {
                            Id = new Guid("6a9dc62c-93c2-4043-a154-aafd68add68b"),
                            DateCreated = new DateTime(2024, 1, 16, 15, 27, 0, 223, DateTimeKind.Local).AddTicks(3267),
                            Description = "eliminar una tarea",
                            IsCompleted = true,
                            IsDeleted = false,
                            NameTask = "Tarea 50",
                            UserId = new Guid("a73c074a-cf36-42d7-a21d-c2912ac8031a")
                        });
                });

            modelBuilder.Entity("TemplateCRUDNet7.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("USER");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a73c074a-cf36-42d7-a21d-c2912ac8031a"),
                            Email = "diegop177@hotmail.com",
                            Name = "Diego Parra",
                            Password = "diego1234"
                        },
                        new
                        {
                            Id = new Guid("09545053-100d-4d65-b5f4-30dc76de76f5"),
                            Email = "laura@gmail.com",
                            Name = "Laura",
                            Password = "laura1234"
                        },
                        new
                        {
                            Id = new Guid("3c85ef10-5ed2-4563-9f2d-600f9d01397b"),
                            Email = "pilar@gmail.com",
                            Name = "Pilar",
                            Password = "pilar1234"
                        });
                });

            modelBuilder.Entity("TemplateCRUDNet7.Entities.Tasks", b =>
                {
                    b.HasOne("TemplateCRUDNet7.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
